name: Publish Picta-FDM plugin

on: push

permissions:
  contents: write  # IMPORTANT: mandatory for making GitHub Releases
      
jobs:
  build_plugin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Compress plugin Directory
        uses: somaz94/compress-decompress@v1
        with:
          command: compress
          source: ./plugin
          format: zip
          includeRoot: 'false'
          
      - name: Rename plugin
        run: |
            mv ${{ github.workspace }}/plugin/plugin.zip ${{ github.workspace }}/plugin/picta-fdm.fda
  github-release:
    runs-on: ubuntu-latest

    steps:
      - name: Sign the plugin with Sigstore
        uses: sigstore/gh-action-sigstore-python@v3.0.0
        with:
          input:
            ${{ github.workspace }}/plugin/picta-fdm.fda

      - name: Upload plugin to GitHub Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run:
          gh release upload
          '${{ github.ref_name }}' ${{ github.workspace }}/plugin/picta-fdm.*
          --clobber
          --repo '${{ github.repository }}'
